### ISSUE TITLE
Drawer width is not flexible

### ISSUE THREAD

**Issue by sevcsik** [PolymerElements/paper-drawer-panel#58]
According to the [spec](http://www.google.com/design/spec/patterns/navigation-drawer.html#navigation-drawer-specs), the drawer panel width should be 100% minus the height of the action bar (56px), or 280px on mobile, and 320px on tablet.

Currently this needs to be worked around outside the element, because it only supports a fixed number via the `drawerWidth` property.

I came up with a simple CSS rule which can implement this (for mobile):

``` css
paper-drawer-panel #drawer {
  width: calc(100% - 56px) !important;
  max-width: 280px;
}
```

But this is a bit ugly, because I have to use `!important` to override the `style` attribute used inside the element, and also breaks the always-open mode on large screens.
