### ISSUE TITLE
Why the transition on the paper-drawer-panel is on ease-in-out?

### ISSUE THREAD

**Issue by ddadon10** [PolymerElements/paper-drawer-panel#99]
Hi,

Just a question about the transition on the paper-drawer-panel :

When the **drawer** is hide (e.g : on mobile) you can swipe on the edge for display the panel : OK

But the CSS transition has a little "glitch" i think, because you can see a little "lag" when you slide from the edge (specifically when you detach your finger from the screen before the panel is fully extended)

**I've seen that the transition is on "ease-in-out". And it's more fluid if i set the transition on "ease-out" or "out-quadratic"**

So : Why the polymer dev team put the transition on "ease-in-out" ?

Thanks ! :)

Don't hesitate to contact me if you want more explanation about my issue !

Oh, and sorry for my english !

**Comment by blasten** [comment]
Feel free to send a PR and make this a custom property. e.g.  `--paper-drawer-panel-timing-function`. The default could be `ease-out`

**Comment by WoodyWoodsta** [comment]
Would the user not want to specify the transition duration as well (as I would like to :smile: ). I would submit a PR but there is one already. But here is a suggestion with a `--paper-drawer-panel-transition-duration` custom property included (related to https://github.com/PolymerElements/paper-drawer-panel/pull/110#issuecomment-166938234):

``` css
.transition > #drawer {
  transition-property: transform, width, visibility;
  -webkit-transition-property: -webkit-transform, width, visibility;

  transition-timing-function: var(--paper-drawer-panel-timing-function, ease-out);
  -webkit-transition-timing-function: var(--paper-drawer-panel-timing-function, ease-out);

  transition-duration: var(--paper-drawer-panel-transition-duration, 0.3s);
  -webkit-transition-duration: var(--paper-drawer-panel-transition-duration, 0.3s);
}
```
